
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Feb 17 10:03:45 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 24;
  public static final int CHAR = 51;
  public static final int CONST = 26;
  public static final int NOTEQUAL = 40;
  public static final int GREATER = 41;
  public static final int CONTINUE = 35;
  public static final int LPAREN = 22;
  public static final int SEMI = 20;
  public static final int LESS = 43;
  public static final int MINUS = 12;
  public static final int RPAREN = 23;
  public static final int AND = 45;
  public static final int RECORD = 38;
  public static final int EQUALTO = 39;
  public static final int OR = 46;
  public static final int BOOL = 49;
  public static final int COMMA = 21;
  public static final int CLASS = 28;
  public static final int INC = 17;
  public static final int DIV = 14;
  public static final int DOUBLEDOT = 19;
  public static final int PLUS = 11;
  public static final int IF = 31;
  public static final int THIS = 36;
  public static final int DOT = 47;
  public static final int EOF = 0;
  public static final int RETURN = 6;
  public static final int RBRACKET = 25;
  public static final int EQUAL = 16;
  public static final int SUPER = 37;
  public static final int NEW = 3;
  public static final int error = 1;
  public static final int MUL = 13;
  public static final int NUMBER = 50;
  public static final int MOD = 15;
  public static final int IDENT = 48;
  public static final int BREAK = 27;
  public static final int VOID = 8;
  public static final int LESSOREQL = 44;
  public static final int LBRACE = 7;
  public static final int ELSE = 30;
  public static final int ENUM = 29;
  public static final int READ = 5;
  public static final int GOTO = 9;
  public static final int WHILE = 33;
  public static final int RBRACE = 10;
  public static final int EXTENDS = 34;
  public static final int PROG = 2;
  public static final int DEC = 18;
  public static final int GRTOREQL = 42;
  public static final int PRINT = 4;
  public static final int DO = 32;
}

